spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://remotemysql.com:3306/xKisX4cejF
    username: xKisX4cejF
    password: dTqGwLj3TL

    initialization-mode: always

  jpa:
    hibernate:
      show_sql: true
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
